### ISSUE TITLE
Implement log estructur and util classes

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-java#20]
# Description
Integrate a logging service to improve logging capabilities and facilitate better debugging and monitoring. To achieve this, implement Logback as main framework and configuring it using a `logback.xml` file in order to have multiple loggers available.

# Tasks
- [x] Add Logback Dependency
- [x] Create logback.xml Configuration File
- [x] Integrate Logback into the Project
